<?php

namespace AppBundle\Repository;

/**
 * catSnackRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CatSnackRepository extends \Doctrine\ORM\EntityRepository
{
}
