<?php

namespace AppBundle\Repository;

/**
 * snackRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class snackRepository extends \Doctrine\ORM\EntityRepository
{
}
