<?php

namespace AppBundle\Repository;

/**
 * trancheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class trancheRepository extends \Doctrine\ORM\EntityRepository
{
}
