<?php
/**
 * Created by PhpStorm.
 * User: lapiscine
 * Date: 2018-12-04
 * Time: 14:05
 */

namespace AppBundle\Repository;

/**
 * VerifTrancheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VerifTrancheRepository extends \Doctrine\ORM\EntityRepository
{

}
